### PR TITLE
using stub instead of spy on publish and sendToQueue

### PR DESCRIPTION
**Pull request by melalj**
Per ticket: https://github.com/tjmehta/coworkers-test/issues/9

### CODE REVIEW

**Comment by tjmehta** [comment]
Thanks! Checking this out in a few

**Comment by tjmehta** [comment]
K catching up on this now. Any ideas on some good tests to add for the broken case?

**Comment by tjmehta** [comment]
Maybe I should add assertions for publish methods as a feature

**Comment by tjmehta** [comment]
@melalj, I added some tests for this and realized `context.publisherChannel` used to be `context.producerChannel` in a very early version of coworkers. `coworkers-test` was never made compatible w/ the change.

https://github.com/tjmehta/coworkers-test/blob/master/lib/mock-context-factory.js#L16

**Comment by melalj** [comment]
Good! there's already stubs for the publish method, and we have access to the context on the expect.

**Comment by tjmehta** [comment]
Fixed coworkers-test@0.3.1. Thanks for the ticket and PR! lmk if you hit any other problems.

**Pull request closed without merging**
